name: Deploy VitePress site to Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          node-version: 20
          cache: npm
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        run: npm ci
      - name: Add config.js
        run: |
          echo "module.exports = {" > docs/.vitepress/config.js
          echo "  title: 'Attest Documentation'," >> docs/.vitepress/config.js
          echo "  themeConfig: {" >> docs/.vitepress/config.js
          echo "    nav: [" >> docs/.vitepress/config.js
          echo "      { text: 'Home', link: '/' }," >> docs/.vitepress/config.js
          echo "      { text: 'About', link: '/about/' }," >> docs/.vitepress/config.js
          echo "      { text: 'Contact', link: '/contact' }" >> docs/.vitepress/config.js
          echo "    ]," >> docs/.vitepress/config.js
          echo "    sidebar: [" >> docs/.vitepress/config.js
          echo "      {" >> docs/.vitepress/config.js
          echo "        text: 'Attest Installation'," >> docs/.vitepress/config.js
          echo "        collapsed: false," >> docs/.vitepress/config.js
          echo "        items: [" >> docs/.vitepress/config.js
          echo "          { text: 'Attest Installation', link: '/about/attestinstallation' }" >> docs/.vitepress/config.js
          echo "        ]" >> docs/.vitepress/config.js
          echo "      }," >> docs/.vitepress/config.js
          echo "      {" >> docs/.vitepress/config.js
          echo "        text: 'Attest Functionalities'," >> docs/.vitepress/config.js
          echo "        collapsed: false," >> docs/.vitepress/config.js
          echo "        items: [" >> docs/.vitepress/config.js
          echo "          { text: 'Attest Track', link: 'https://github.com/Priya140895/VitePress_Documentation/blob/main/docs/about/attesttrack.md' }," >> docs/.vitepress/config.js          echo "          { text: 'Attest Functions', link: 'VitePress_Documentation/about/attestfunctions' }" >> docs/.vitepress/config.js
          echo "        ]" >> docs/.vitepress/config.js
          echo "      }," >> docs/.vitepress/config.js
          echo "      {" >> docs/.vitepress/config.js
          echo "        text: 'Attest Functionalities'," >> docs/.vitepress/config.js
          echo "        collapsed: false," >> docs/.vitepress/config.js
          echo "        items: [" >> docs/.vitepress/config.js
          echo "          { text: 'Attest Functions', link: '/attestfunc' }" >> docs/.vitepress/config.js
          echo "        ]" >> docs/.vitepress/config.js
          echo "      }" >> docs/.vitepress/config.js
          echo "    ]" >> docs/.vitepress/config.js
          echo "  }" >> docs/.vitepress/config.js
          echo "}" >> docs/.vitepress/config.js
      - name: Build with VitePress
        run: npm run docs:build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: 'https://priya140895.github.io/VitePress_Documentation/'
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
